db:
  host: 'localhost'
  username: 'postgres'
  password: 'someDevelopmentStack'
  synchronize: true

elastic_search:
  node: http://localhost:9200

redis:
  host: localhost

jwt:
  secret: 'topSecretString69'

master_access:
  username: 'root'
  password: 'SomeDankPassword1!'