db:
  host: 'localhost'
  username: 'postgres'
  password: 'someDevelopmentStack'
  synchronize: true

jwt:
  secret: 'topSecretString69'

master_access:
  username: 'root'
  password: 'SomeDankPassword1!'